# Calamares Bootloader Module Configuration for Secura OS
---
efiBootLoader: "grub"

kernel: "/vmlinuz"
img: "/initrd.img"

grubInstall: "grub-install"
grubMkconfig: "grub-mkconfig"
grubCfg: "/boot/grub/grub.cfg"

efiEntryName: "Secura Linux"

installEpTree: true
