# Calamares Locale Module Configuration for Secura OS
---
region:                     "America"
zone:                       "New_York"
localeGenPath:              "/etc/locale.gen"
geoip:
    style:                  "none"
