# Calamares Packages Module Configuration for Secura OS
---
backend: apt

operations:
  - try_remove:
      - live-boot
      - live-boot-doc
      - live-config
      - live-config-doc
      - live-config-systemd
      - calamares
      - calamares-settings-debian
