# Calamares Unpackfs Module Configuration for Secura OS
---
unpack:
    -   source: "/run/live/medium/live/filesystem.squashfs"
        sourcefs: "squashfs"
        destination: ""
        weight: 10
