# Calamares Users Module Configuration for Secura OS
---
defaultGroups:
    - sudo
    - netdev
    - audio
    - video
    - plugdev
    - input
    - cdrom

autologinGroup:        autologin
sudoersGroup:          sudo
setRootPassword:       false
doAutologin:           false
hideCreateUser:        false
userNeedsPassword:     true

passwordRequirements:
    nonempty: true
    minLength: 6
